inherit_from: configs/ScanNet/scannet.yaml
data:
  input_path: /mnt/data3/dataset/scannet_after/scene0054_00
  output_path: /mnt/data3/bayesianSLAM_GS/ScanNet/scene0054
  scene_name: scene0054_00
cam: 
  H: 480 
  W: 640
  fx: 578.0
  fy: 578.0
  cx: 319.5
  cy: 239.5
  depth_scale: 1.
  crop_edge: 12

var:
  use_nlldepth: False
